In [16]:
import pandas as pd

In [17]:
products_df = pd.read_csv("blinkit_products.csv")
orders_df = pd.read_csv("blinkit_orders.csv")
orders_items_df = pd.read_csv("blinkit_order_items.csv")

In [18]:
products_df.shape
orders_df.shape
orders_items_df.shape

(5000, 4)

In [19]:
products_df.info()
products_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    int64
 1   product_name       268 non-null    object
 2   category           268 non-null    object
 3   brand              268 non-null    object
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: float64(3), int64(4), object(3)
memory usage: 21.1+ KB

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55

In [20]:
orders_df.info()
orders_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   object
 3   promised_delivery_time  5000 non-null   object
 4   actual_delivery_time    5000 non-null   object
 5   delivery_status         5000 non-null   object
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   object
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: float64(1), int64(4), object(5)
memory usage: 390.8+ KB

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

In [21]:
orders_items_df.info()
orders_items_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5000 non-null   int64
 1   product_id  5000 non-null   int64
 2   quantity    5000 non-null   int64
 3   unit_price  5000 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 156.4 KB

     order_id  product_id  quantity  unit_price
0  1961864118      642612         3      517.03
1  1549769649      378676         1      881.42
2  9185164487      741341         2      923.84
3  9644738826      561860         1      874.78
4  5427684290      602241         2      976.55

In [22]:
orders_df['order_date'] = pd.to_datetime(orders_df['order_date'])
orders_df['promised_delivery_time'] = pd.to_datetime(orders_df['promised_delivery_time'])
orders_df['actual_delivery_time'] = pd.to_datetime(orders_df['actual_delivery_time'])

orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   datetime64[ns]
 3   promised_delivery_time  5000 non-null   datetime64[ns]
 4   actual_delivery_time    5000 non-null   datetime64[ns]
 5   delivery_status         5000 non-null   object
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   object
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: datetime64[ns](3), float64(1), int64(4), object(2)
memory usage: 390.8+ KB

In [23]:
products_df.isnull().sum()

product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64

In [24]:
products_df.duplicated().sum()

np.int64(0)

In [25]:
orders_df.isnull().sum()
orders_df.duplicated().sum()

orders_items_df.isnull().sum()
orders_items_df.duplicated().sum()

np.int64(0)

In [28]:
orders_df["delivery_delay_minutes"] = (orders_df["actual_delivery_time"]-orders_df["promised_delivery_time"]).dt.total_seconds()/60

orders_df[['promised_delivery_time', 'actual_delivery_time', 'delivery_delay_minutes']].head()

  promised_delivery_time actual_delivery_time  delivery_delay_minutes
0    2024-07-17 08:52:01  2024-07-17 08:47:01                    -5.0
1    2024-05-28 13:25:29  2024-05-28 13:27:29                     2.0
2    2024-09-23 13:25:12  2024-09-23 13:29:12                     4.0
3    2023-11-24 16:34:56  2023-11-24 16:33:56                    -1.0
4    2023-11-20 05:17:39  2023-11-20 05:18:39                     1.0

In [30]:
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('mysql+pymysql://root:XXXXXX@127.0.0.1:3306/blinkit_db')

In [45]:
products_df.to_sql('products', con=engine, if_exists='replace', index=False)

orders_df.to_sql('orders', con=engine, if_exists='replace', index=False)

orders_items_df.to_sql('order_items', con=engine, if_exists='replace', index=False)

5000